### ISSUE TITLE
Trapped chests isn't always closes

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#6865]
### Expected behavior

Trapped chest closed and can be used again...

### Observed/Actual behavior

Trapped chest isn't closed and can't provide a redstone signal anymore...

### Steps/models to reproduce

Place a command block with `effect give @p minecraft:levitation 1 100`
Place a trapped chest above it
Stand up on the trapped chest
Open it

You will be launched into the space for one second, but after successful landing, chest may be broken. Yea, this isn't happen every time, but I can reproduce this bug in almost 2-4 "flights".

### Plugin and Datapack List

Plugins — 0
There are 2 data packs enabled: [vanilla (built-in)], [file/Bukkit (world)]

### Paper version

This server is running Paper version git-Paper-353 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)
You are 6 version(s) behind

Update: Tested on the build 359 too

### Other

![image](https://user-images.githubusercontent.com/19989717/140178267-384f7aed-84fc-4471-b5d9-ba5acb2c66a0.png)

**Comment by Machine-Maker** [comment]
Yeah, replicated this. didnt' work on first open, but after the second open the chest doesn't seem to output any signal. A server restart did fix the issue, so I'm guessing a chunk unload/load would fix it as well.

**Comment by molor** [comment]
> chunk unload/load would fix it as well

Hmm, I'm tried to leave chest for a minute and after going back it was closed, but after open it doesn't output signal anyway and remains open again..

Update: Maybe it's because I was doing this on the `keep-spawn-loaded` chunks

**Comment by lynxplay** [comment]
I was capable of reproducing this (in addition to MM on paper) on spigot (`3273-Spigot-3892929-376edf4`) as well as on minecraft 1.17.1.

This issue is most certainly a duplicate of https://bugs.mojang.com/browse/MC-229680, however in vanilla the chest remains closed after existing the chests UI through a too big distance.

**Comment by lynxplay** [comment]
For anyone interested in giving this a shot, it should be a rather fun PR as it dives somewhat deep into block ticking and the chest/trapped-chest/barrel code.

Basic issue *seems (maybe I overlooked something)* to be the following:

1. Blocks are ticked internally prior to entities, including players.
2. Players have individual logic to actively close (and decrease the open counter) of their active container (see [here](https://github.com/PaperMC/Paper/blob/master/patches/server/0407-Prevent-opening-inventories-when-frozen.patch#L16)  or `ServerPlayer.java:641`).
3. This logic (`RandomizableContainerBlockEntity#stillValid(Player)`) will no longer consider a player as viewing the inventory when further away than 8 blocks from the inventory blocks centre, decreasing the open viewer count.
4. Enderchests, (Trapped)Chests and barrels all re-check the amount of players that currently are accessing them using `ChestBlockEntity#recheckOpen` or the likes.
5. The `recheckOpen` method delegates to `ContainerOpenersCounter#getOpenCount` and will no longer consider players as valid viewer when they are outside a `10x10x10` bounding box centred at the blocks location.
6. `ContainerOpenersCounter#getOpenCount` will decrease the open count but will not notify/update players if they are no longer viewing the containers inventory.

From these facts, it seems like there *might* be a tick in which the container's `recheckOpen` will not consider a player as a viewer while the player itself has not yet realized that fact, mainly in the tick, **call it `N0` when the player is outside the 10x10x10 AABB centred at the container while still inside the sphere with an 8 block radius**.

The open count would hence be reset to **0** by the `recheckOpen` method in tick `N0`.
The player will now, in a tick after `N0` move outside the 8 block radius sphere and actively decrement the open count on the container once more, leaving it at `-1`.

Considering that mojang loves to use `i == 0` instead of `i <= 0` in a lot of places, such as `ContainerOpenersCounter.java:65`, no closing animation will be played when the counter drops to `-1`.
In regards to the trapped chest, `TrappedChestBlock#getSignal` uses the upper mentioned open counter, which is now shifted to `-1` when closed and `0` when opened and hence do not output a signal in either case.

**Comment by molor** [comment]
This is currently fixed only in 1.17.1 branch, correct?

**Comment by electronicboy** [comment]
Literally never knew there was even an issue open for this, but, yea, was only fixed in 1.17 as it was reported to me through a server I do dev stuff for

at least for me, just preventing the number from going negative prevented this, it did seem like the logic to recount the slots would fire and keep stuff enough in wack that just preventing it from going negative when removing is enough to resolve this without wider changes

**Comment by molor** [comment]
(this is still an issue in latest experimental build, if it's important)
