### ISSUE TITLE
Player Yaw Ignored on Spawn

### ISSUE THREAD

**Issue by awesomebrownies** [PaperSpigot/Paper#9544]
### Expected behavior

When the player spawns in, their yaw should not face south

### Observed/Actual behavior

Their yaw faces south

### Steps/models to reproduce

Install Paper 1.20.1
Login a player and make them face north

Logout and login and look at the player without them moving their head.
OR
Go outside player range and go back in

### Plugin and Datapack List

None

### Paper version

[19:24:03 INFO]: [97mThis server is running Paper version git-Paper-83 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c793bd9)[0m
[3m[37mPrevious version: git-Paper-68 (MC: 1.20.1)[0m

### Other

This issue was not reproducible in 1.18.2

**Comment by Evan-27-dev** [comment]
![Screenshot 2023-07-28 153126](https://github.com/PaperMC/Paper/assets/46765400/70ad965a-e6fb-4d82-a365-603ec53790c1)

**Comment by molor** [comment]
Probably fixed in upstream by https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/a2fafdd1d2f0f70f378dfda714147c2a202c4c16

**Comment by Evan-27-dev** [comment]
Got it. I'll open this back up if I have issues when I update the server.

**Comment by Evan-27-dev** [comment]
Issue still occurs 
[18:00:36 INFO]: [97mThis server is running Paper version git-Paper-98 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a40e48f)[0m

**Comment by Warriorrrr** [comment]
Upstream hasn't been pulled in yet, once it's pulled it'll be fixed
